# Generated by Django 6.0.2 on 2026-05-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_alter_equipment_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='code',
            field=models.CharField(default='null', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
