# Generated by Django 6.0.2 on 2026-02-25 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='type',
        ),
    ]
