# Generated by Django 6.0.2 on 2026-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organisation_company_address_organisation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
