# Generated by Django 6.0.2 on 2026-03-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employee_id',
            new_name='user_id',
        ),
    ]
