# Generated by Django 6.0.2 on 2026-04-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_servicerequest_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='code',
            field=models.CharField(default='null', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
