# Generated by Django 6.0.2 on 2026-04-09 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicerequest_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='name',
            new_name='company_name',
        ),
    ]
