# Generated by Django 6.0.2 on 2026-04-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_name_servicerequest_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='custom_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
