# Generated by Django 6.0.2 on 2026-04-19 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicerequest_custom_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['-created_at']},
        ),
    ]
