[build]
builder = "nixpacks"

[deploy]
startCommand = "daphne -b 0.0.0.0 -p $PORT bismak.asgi:application"
preDeployCommand = "python manage.py migrate --noinput"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[env]
DJANGO_SETTINGS_MODULE = "bismak.settings.prod"