# Generated by Django 6.0.2 on 2026-04-19 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_alter_invoice_quote_alter_quote_amount_quoteitem'),
        ('projects', '0012_remove_leaktest_executed_by_and_more'),
        ('services', '0006_alter_servicerequest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='revision_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quote',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='service_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='services.servicerequest'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='QuoteRevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='billings.quote')),
                ('revised_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_revisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
