# Generated by Django 6.0.2 on 2026-05-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_alter_invoice_status_alter_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
