# Generated by Django 6.0.2 on 2026-02-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_project_created_by_project_name_project_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
