# Generated by Django 6.0.2 on 2026-03-01 14:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_start_date_alter_project_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeakTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date_of_test', models.DateField()),
                ('expiring_date', models.DateField()),
                ('equipment_tested', models.CharField(max_length=255)),
                ('result', models.CharField(choices=[('satisfactory', 'Satisfactory'), ('unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leak_test', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeakTestTank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tank_no', models.PositiveIntegerField()),
                ('product_stored', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('age_of_tank', models.PositiveIntegerField()),
                ('date_of_test', models.DateField()),
                ('remark', models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('fair', 'Fair')], max_length=20)),
                ('leak_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='projects.leaktest')),
            ],
            options={
                'ordering': ['tank_no'],
            },
        ),
        migrations.CreateModel(
            name='PressureTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.CharField(max_length=255)),
                ('location_address', models.CharField(max_length=255)),
                ('manufacturer', models.CharField(max_length=255)),
                ('manufacturing_date', models.DateField()),
                ('serial_no', models.CharField(max_length=100)),
                ('truck_no', models.CharField(max_length=100)),
                ('tank_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_stored', models.CharField(max_length=100)),
                ('tank_type', models.CharField(max_length=100)),
                ('test_pressure', models.DecimalField(decimal_places=2, max_digits=8)),
                ('working_pressure', models.DecimalField(decimal_places=2, max_digits=8)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('test_duration', models.PositiveIntegerField()),
                ('test_medium', models.CharField(max_length=100)),
                ('avrg_utm_gauge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('safety_relief_valve_size', models.CharField(max_length=50)),
                ('safety_relief_valve_no', models.PositiveIntegerField()),
                ('date_of_test', models.DateField()),
                ('next_test_date', models.DateField()),
                ('result', models.CharField(choices=[('satisfactory', 'Satisfactory'), ('unsatisfactory', 'Unsatisfactory')], max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pressure_test', to='projects.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
