# Generated by Django 6.0.2 on 2026-03-04 15:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_leaktest_leaktesttank_pressuretest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pressuretest',
            name='date_of_test',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pressuretest',
            name='product_stored',
            field=models.CharField(default='LPG', max_length=100),
        ),
        migrations.AlterField(
            model_name='pressuretest',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pressuretest',
            name='tank_type',
            field=models.CharField(default='Carbon Steel', max_length=100),
        ),
        migrations.AlterField(
            model_name='pressuretest',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pressuretest',
            name='test_duration',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='pressuretest',
            name='test_medium',
            field=models.CharField(default='Hydrostatic', max_length=100),
        ),
    ]
