# Generated by Django 6.0.2 on 2026-03-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectassignment_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
