# Generated by Django 6.0.2 on 2026-03-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectassignment',
            options={'ordering': ['-created_at']},
        ),
    ]
