# Generated by Django 6.0.2 on 2026-03-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectassignment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Pressure_test', 'Pressure Test'), ('Leak_test', 'Leak Test'), ('Calibration', 'Calibration')], max_length=20, null=True),
        ),
    ]
