# Generated by Django 6.0.2 on 2026-03-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaktest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pressuretest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='leaktest',
            name='equipment_tested',
        ),
        migrations.RemoveField(
            model_name='leaktest',
            name='result',
        ),
        migrations.RemoveField(
            model_name='leaktesttank',
            name='age_of_tank',
        ),
        migrations.RemoveField(
            model_name='leaktesttank',
            name='date_of_test',
        ),
        migrations.RemoveField(
            model_name='leaktesttank',
            name='remark',
        ),
        migrations.AddField(
            model_name='leaktest',
            name='age_of_tank',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaktest',
            name='remark',
            field=models.CharField(choices=[('good', 'Good'), ('bad', 'Bad'), ('fair', 'Fair')], default='good', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaktesttank',
            name='product_stored',
            field=models.CharField(choices=[('ago', 'AGO'), ('pms', 'PMS'), ('dpk', 'DPK')], max_length=10),
        ),
    ]
