# Generated by Django 6.0.2 on 2026-03-31 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_leaktest_options_alter_pressuretest_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaktest',
            name='client_representative',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaktest',
            name='dpr_in_charge',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaktest',
            name='executed_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['staff', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leak_tests_executed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pressuretest',
            name='client_representative',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressuretest',
            name='dpr_in_charge',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pressuretest',
            name='executed_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['staff', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pressure_tests_executed', to=settings.AUTH_USER_MODEL),
        ),
    ]
