# Generated by Django 6.0.2 on 2026-04-08 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_leaktest_client_representative_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaktest',
            name='executed_by',
        ),
        migrations.RemoveField(
            model_name='pressuretest',
            name='executed_by',
        ),
        migrations.AddField(
            model_name='project',
            name='executed_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['staff', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
