# Generated by Django 6.0.2 on 2026-05-04 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_remove_leaktest_executed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressuretest',
            name='dpr_in_charge',
        ),
    ]
