# Generated by Django 6.0.2 on 2026-06-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_remove_pressuretest_dpr_in_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaktest',
            name='dpr_in_charge',
        ),
    ]
